// Hold On — trailer renderer.
//   node render.mjs --timeline   rebuild timeline.js only (for previewing trailer.html)
//   node render.mjs              timeline + frames (headless Chrome) + audio mix -> out/hold-on-trailer.mp4
// Voice lines come from babble-lab (../../babble-lab), rendered from lines.txt + cast.json.
import fs from 'node:fs';
import path from 'node:path';
import { spawn, execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const BABBLE = path.resolve(HERE, '../../babble-lab');
const FPS = 30, SR = 44100;
const only = process.argv.includes('--timeline');

// 1. voice
execFileSync(process.execPath, [path.join(BABBLE, 'bin/babble.mjs'), 'script', 'lines.txt', '--cast', 'cast.json', '-o', 'voice', '--quiet'], { cwd: HERE, stdio: 'inherit' });
const man = JSON.parse(fs.readFileSync(path.join(HERE, 'voice/manifest.json'), 'utf8'));

// 2. timeline: when each line starts. The pauses are where the pictures do the talking.
const GAP_AFTER = { 1: 1.0, 3: 0.6, 4: 1.2, 6: 1.2, 7: 0.4, 8: 0.8, 10: 4.0, 11: 1.4 };
let t = 3.6;
const lines = man.lines.map((l, i) => {
  const out = { who: l.who, text: l.text, file: l.file, start: +t.toFixed(3), dur: l.duration, reveal: l.reveal };
  t += l.duration + (GAP_AFTER[i] ?? 0.7);
  return out;
});
const total = +(lines.at(-1).start + lines.at(-1).dur + 6).toFixed(2);
fs.writeFileSync(path.join(HERE, 'timeline.js'), `// generated by render.mjs — do not edit\nwindow.TL = ${JSON.stringify({ total, lines })};\n`);
console.log(`timeline: ${lines.length} lines, ${total.toFixed(1)} s`);
if (only) process.exit(0);

// 3. audio: babble lines over a low drone, a storm swell during the mud
const { decodeWav } = await import(pathToFileURL(path.join(BABBLE, 'src/wav.mjs')).href);
const N = Math.ceil(total * SR), mix = new Float32Array(N);
let lp = 0, lp2 = 0, seed = 12345;
const rnd = () => ((seed = (seed * 1103515245 + 12345) >>> 0) / 4294967296) * 2 - 1;
const stormA = lines[10].start + lines[10].dur + 0.6, stormB = stormA + 3.0;
for (let i = 0; i < N; i++) {
  const s = i / SR;
  const lfo = 0.6 + 0.4 * Math.sin(s * 0.21);
  let v = 0.022 * lfo * (Math.sin(2 * Math.PI * 55 * s) + 0.6 * Math.sin(2 * Math.PI * 82.4 * s + 1) + 0.3 * Math.sin(2 * Math.PI * 110.3 * s));
  lp += 0.012 * (rnd() - lp); lp2 += 0.05 * (lp - lp2);
  const storm = s > stormA && s < stormB ? Math.sin(Math.PI * (s - stormA) / (stormB - stormA)) : 0;
  v += lp2 * (0.9 + storm * 5.5);
  const fade = Math.min(1, s / 1.5, (total - s) / 1.5);
  mix[i] = v * Math.max(0, fade);
}
for (const l of lines) {
  const w = decodeWav(fs.readFileSync(path.join(HERE, 'voice', l.file)));
  if (w.channels !== 1 || w.sampleRate !== SR) throw new Error(`${l.file}: expected mono ${SR} Hz, got ${w.channels} ch ${w.sampleRate} Hz`);
  const ch = w.samples;
  const off = Math.round(l.start * SR);
  for (let k = 0; k < ch.length && off + k < N; k++) mix[off + k] += ch[k] * 0.9;
}
let peak = 0; for (const v of mix) peak = Math.max(peak, Math.abs(v));
const gain = peak > 0.95 ? 0.95 / peak : 1;
const pcm = Buffer.alloc(44 + N * 2);
pcm.write('RIFF', 0); pcm.writeUInt32LE(36 + N * 2, 4); pcm.write('WAVEfmt ', 8);
pcm.writeUInt32LE(16, 16); pcm.writeUInt16LE(1, 20); pcm.writeUInt16LE(1, 22); pcm.writeUInt32LE(SR, 24);
pcm.writeUInt32LE(SR * 2, 28); pcm.writeUInt16LE(2, 32); pcm.writeUInt16LE(16, 34); pcm.write('data', 36); pcm.writeUInt32LE(N * 2, 40);
for (let i = 0; i < N; i++) pcm.writeInt16LE(Math.round(Math.max(-1, Math.min(1, mix[i] * gain)) * 32767), 44 + i * 2);
fs.mkdirSync(path.join(HERE, 'out'), { recursive: true });
const wavPath = path.join(HERE, 'out/mix.wav');
fs.writeFileSync(wavPath, pcm);
console.log(`audio: peak ${peak.toFixed(3)}, gain ${gain.toFixed(3)}`);

// 4. frames -> ffmpeg
const FFMPEG = process.env.FFMPEG || execFileSync('python', ['-c', 'import imageio_ffmpeg as f;print(f.get_ffmpeg_exe())']).toString().trim();
const CHROME = process.env.CHROME || 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const { default: puppeteer } = await import('puppeteer-core');
const browser = await puppeteer.launch({ executablePath: CHROME, headless: true, args: ['--allow-file-access-from-files', '--force-device-scale-factor=1'] });
const page = await browser.newPage();
await page.setViewport({ width: 1080, height: 1920 });
await page.goto(pathToFileURL(path.join(HERE, 'trailer.html')).href + '?render');
await page.evaluate(() => window.ready());
const qrOk = await page.evaluate(() => { const i = new Image(); i.src = '../qr-crinoid.png'; return new Promise(r => { i.onload = () => r(i.naturalWidth > 0); i.onerror = () => r(false); }); });
if (!qrOk) throw new Error('QR image did not load in the render page');

const out = path.join(HERE, 'out/hold-on-trailer.mp4');
const ff = spawn(FFMPEG, ['-y', '-loglevel', 'error', '-f', 'image2pipe', '-framerate', String(FPS), '-c:v', 'mjpeg', '-i', '-',
  '-i', wavPath, '-c:v', 'libx264', '-preset', 'medium', '-crf', '19', '-pix_fmt', 'yuv420p', '-movflags', '+faststart',
  '-c:a', 'aac', '-b:a', '160k', '-shortest', out], { stdio: ['pipe', 'inherit', 'inherit'] });
const frames = Math.ceil(total * FPS);
const t0 = Date.now();
for (let f = 0; f < frames; f++) {
  const b64 = await page.evaluate((tt) => { window.draw(tt); return document.getElementById('c').toDataURL('image/jpeg', 0.93).slice(23); }, f / FPS);
  if (!ff.stdin.write(Buffer.from(b64, 'base64'))) await new Promise(r => ff.stdin.once('drain', r));
  if (f % 150 === 0) console.log(`frame ${f}/${frames}  ${((Date.now() - t0) / 1000).toFixed(0)} s`);
}
ff.stdin.end();
await new Promise((res, rej) => ff.on('close', c => c === 0 ? res() : rej(new Error('ffmpeg exit ' + c))));
await browser.close();
console.log(`wrote ${out}  ${(fs.statSync(out).size / 1e6).toFixed(1)} MB, ${frames} frames`);
